name: Todo

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  todo:
    name: Run todo scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: "actions/checkout@master"
      - name: Run Todo
        uses: "alstr/todo-to-issue-action@v4"
        id: "todo"
